version: "3.7"

services:
  db:
    container_name: ponder-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  studio:
    build:
      context: ./
      dockerfile: Dockerfile
      target: studio
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_BASE_URL: ${VITE_BACKEND_BASE_URL}

  studio-service:
    build:
      context: ./
      dockerfile: Dockerfile
      target: studio-service
    ports:
      - 3010:3010
    environment:
      DATABASE_URL: ${DATABASE_URL}

  service:
    build:
      context: ./
      dockerfile: Dockerfile
      target: service
    ports:
      - 3100:3100
    environment:
      DATABASE_URL: ${DATABASE_URL}

  test:
    build:
      context: ./
      dockerfile: Dockerfile
      target: test

  seed-db:
    build:
      context: ./
      dockerfile: Dockerfile
      target: seed-db
    environment:
      DATABASE_URL: ${DATABASE_URL}
